// Single source for the gallery. projects.json is generated by the bot
// (channels/scripts/export-gallery.mjs) and committed here, like levels.json.
import data from "../data/projects.json" with { type: "json" };

export const TYPE_LABELS = {
  "web-app": "Web app",
  cli: "CLI",
  bot: "Bot",
  api: "API",
  mobile: "Mobile",
  game: "Game",
  library: "Library",
  other: "Other",
};

function valid(c) {
  return (
    c &&
    typeof c.github === "string" &&
    typeof c.title === "string" &&
    typeof c.repo_url === "string" &&
    TYPE_LABELS[c.type]
  );
}

export function getProjects() {
  return (Array.isArray(data) ? data : [])
    .filter(valid)
    .map((c) => ({
      ...c,
      stack: Array.isArray(c.stack) ? c.stack : [],
      team: Number(c.team) || null,
    }))
    .sort((a, b) => (a.name || a.github).localeCompare(b.name || b.github));
}

// Teams that own at least one personal project, ascending by team number.
// Drives the gallery's team filter; cards with no roster row are excluded.
export function teamBuckets(cards) {
  const m = new Map();
  for (const c of cards) {
    if (!c.team) continue;
    m.set(c.team, (m.get(c.team) || 0) + 1);
  }
  return [...m.entries()]
    .map(([team, count]) => ({ team, count }))
    .sort((a, b) => a.team - b.team);
}

export function typeBuckets(cards) {
  const m = new Map();
  for (const c of cards) m.set(c.type, (m.get(c.type) || 0) + 1);
  return [...m.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count || a.type.localeCompare(b.type));
}

export function stackList(cards) {
  const m = new Map();
  for (const c of cards) for (const s of c.stack) m.set(s, (m.get(s) || 0) + 1);
  return [...m.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}
