// Single source for the team gallery. teams.json is generated by the bot
// (channels/scripts/export-team-gallery.mjs) and committed here, like projects.json.
import data from "../data/teams.json" with { type: "json" };

export const TEAM_TYPE_LABELS = {
  "web-app": "Web app",
  cli: "CLI",
  bot: "Bot",
  api: "API",
  mobile: "Mobile",
  game: "Game",
  library: "Library",
  other: "Other",
};

function valid(t) {
  return (
    t &&
    typeof t.repo_url === "string" &&
    typeof t.title === "string" &&
    TEAM_TYPE_LABELS[t.type]
  );
}

export function hasVideo(t) {
  return Boolean(t && (t.youtube_id || t.drive_id));
}

export function getTeams() {
  return (Array.isArray(data) ? data : [])
    .filter(valid)
    .map((t) => ({ ...t, stack: Array.isArray(t.stack) ? t.stack : [] }))
    .sort((a, b) => (a.team_no ?? 999) - (b.team_no ?? 999));
}

export function typeBuckets(teams) {
  const m = new Map();
  for (const t of teams) m.set(t.type, (m.get(t.type) || 0) + 1);
  return [...m.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count || a.type.localeCompare(b.type));
}

export function statusBuckets(teams) {
  let live = 0,
    done = 0;
  for (const t of teams) {
    if (t.live_url) live++;
    if (t.uploaded === "Done") done++;
  }
  return [
    { status: "live", count: live },
    { status: "done", count: done },
  ];
}
